#!/usr/bin/python3
import whois
import re
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-F', '--file', required=True, help='File containing IP addresses you would like to check for ownership')
args = parser.parse_args()

knownAddresses = []

def checkFile():
    iplist = []
    with open(args.file, "rb") as file:
        data = file.read()
        # .txt files are encoded in uft-8, with this we need to read in as bytes and decode.
        decoded_data = data.decode('utf-8', 'ignore') 
        # This will not read in as each line, so we need splitlines with this.
        for line in decoded_data.splitlines():
            isIP = re.search("^IP Address: (?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$", line)
            if isIP:
                # This will grab the IP address only, as the regex will match the line including "IP Address: "
                iplist.append(line.split(" ")[2].rstrip()) 
    iplist = set(iplist) # Turning the list into a set to only allow for unique instances of IP adddresses
    # Return iplist
    whoisInfo(iplist)

def whoisInfo(iplist):
    print('\n===== Whois Information =====\n')
    for ip in iplist:
        try:
            print("IP address: " + ip)
            info = whois.whois(ip)
            if info.registrar: # Does this to check if the IP is local
                knownAddresses.extend([ip, info.org, info.registrar]) # extends list to add original ip, org, and registrar of IP
        except whois.parser.PywhoisError: 
            print(f'No match for "{ip}"')

def printOutput():
    # Grab the original text file intput by the user, then append _list.txt to it
    with open(str(args.file.split(".")[0]) + "_list.txt", "w") as outputFile:
        for i, item in enumerate(knownAddresses):
            if i % 3 == 2: # After 3 items, start on a new line
                outputFile.write(f"{item}\n")
            else:
                outputFile.write(f"{item} - ")
    print("\nOutput file: " + str(args.file.split(".")[0] + "_list.txt"))

def main():
    checkFile()
    printOutput()

if __name__ == "__main__":
    main()
